spring:
  data:
    redis:
      host: your_redis_host
      port: 12345
      username: your_redis_username
      password: your_redis_password
      ssl:
        enabled: true

  mongodb:
    uri: your_mongodb_uri
    database: journaldb
    auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_gmail_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    key: your_weather_api_key

jwt:
  secret: your_jwt_secret_key